"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "zh" | "ja";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Header
    "nav.about": "About",
    "nav.portfolio": "Portfolio",
    "nav.insights": "Insights",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.dashboard": "Dashboard",

    // Home page
    "home.title": "AI-Powered\nFinancial Innovation",
    "home.subtitle": "Revolutionary AI solutions for quants systems, investment analysis, and trading automation",
    "home.contact": "Contact Us",
    "home.cta": "Start Trading",
    "home.learn": "Learn More",

    // Dashboard
    "dashboard.title": "SAIL Lab Dashboard",
    "dashboard.subtitle": "Multi-Agent AI Trading System & Real-time Market Analysis",
    "dashboard.agents": "AI Agents Online",
    "dashboard.refresh": "Refresh",

    // Portfolio
    "portfolio.title": "Our Portfolio",
    "portfolio.subtitle": "Comprehensive AI-powered solutions transforming financial services through innovation, automation, and intelligent decision-making",
    "portfolio.coreServices": "Core Services",
    "portfolio.customSolutions": "Custom AI Financial Solutions",
    "portfolio.customDesc": "Beyond our core offerings, we develop bespoke AI solutions tailored to your specific financial challenges. From regulatory compliance automation to custom trading algorithms, our team delivers enterprise-grade solutions.",
    "portfolio.regulatoryAI": "Regulatory AI",
    "portfolio.regulatoryDesc": "Automated compliance monitoring and reporting",
    "portfolio.customAlgorithms": "Custom Algorithms",
    "portfolio.customAlgDesc": "Proprietary trading strategy development",
    "portfolio.ctaTitle": "Ready to Accelerate Your Financial AI Journey?",
    "portfolio.ctaDesc": "Schedule a consultation to explore how our AI solutions can transform your financial operations and drive sustainable growth.",
    "portfolio.scheduleConsult": "Schedule Consultation",
    "portfolio.viewPricing": "View Pricing Details",
    "portfolio.multiAgentTitle": "Multi LLM Agent based Stock Analysis (In Dashboard)",
    "portfolio.multiAgentCategory": "Investment Research",
    "portfolio.multiAgentDesc": "Investment analysis using collaborative AI agents providing market insights and investment reports",
    "portfolio.multiAgentFeature1": "Real-time market sentiment analysis",
    "portfolio.multiAgentFeature2": "Multi-source data aggregation",
    "portfolio.multiAgentFeature3": "Automated research reports",
    "portfolio.multiAgentFeature4": "Risk factor identification",
    "portfolio.multiAgentFeature5": "Portfolio optimization recommendations",
    "portfolio.neuralNetworkTitle": "Neural Network Quantitative Trading (See Back Test Result in INSIGHTS)",
    "portfolio.neuralNetworkCategory": "Trading Systems",
    "portfolio.neuralNetworkDesc": "Adaptive neural network trading systems with real-time market optimization",
    "portfolio.neuralNetworkFeature1": "Deep learning price prediction",
    "portfolio.neuralNetworkFeature2": "Adaptive strategy optimization",
    "portfolio.neuralNetworkFeature3": "Real-time risk management",
    "portfolio.neuralNetworkFeature4": "Multi-asset class support",
    "portfolio.neuralNetworkFeature5": "High-frequency execution",
    "portfolio.communityTitle": "AI Trader Community",
    "portfolio.communityCategory": "Platform & Education",
    "portfolio.communityDesc": "Platform connecting AI traders and investors with strategy sharing and performance analytics",
    "portfolio.communityFeature1": "Strategy backtesting environment",
    "portfolio.communityFeature2": "AI model marketplace",
    "portfolio.communityFeature3": "Educational workshops",
    "portfolio.communityFeature4": "Peer-to-peer learning",
    "portfolio.communityFeature5": "Performance analytics dashboard",
    "portfolio.keyFeatures": "Key Features",
    "portfolio.popular": "POPULAR",
    "portfolio.enterprise": "ENTERPRISE",
    "portfolio.beta": "BETA",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.subtitle": "These Terms of Service govern your use of SAIL Lab's AI-powered trading platform. Please read these terms carefully before using our services.",
    "terms.effectiveDate": "Effective Date: January 1, 2025",
    "terms.version": "Version 2.0",
    "terms.riskNotice": "Important Financial Risk Notice",
    "terms.highRiskWarning": "HIGH RISK INVESTMENT WARNING: Trading and investing carry substantial risk of financial loss.",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Your privacy is important to us. This Privacy Policy explains how SAIL Lab collects, uses, and protects your personal information when you use our AI trading platform.",
    "privacy.lastUpdated": "Last Updated: January 1, 2025",

    // About Page
    "about.title": "About SAIL Lab",
    "about.subtitle": "Pioneering the future of financial technology through advanced AI research and cutting-edge multi-agent systems",
    "about.mission": "Our Mission",
    "about.missionText1": "Our core mission is to empower individuals and organizations with cutting-edge tools for portfolio management, driven by our proprietary LLM-based multi-agent analysis engine.",
    "about.missionText2": "Developed by a team of AI researchers and financial experts, our technology continuously monitors and analyzes global markets, financial news, and institutional insights—offering dynamic, data-driven recommendations with human-level understanding.",
    "about.team": "Meet Our Team",
    "about.ceo": "CEO & Founder",
    "about.ceoDesc": "Leading SAIL Lab's vision for democratizing AI-powered financial analysis",
    "about.jayneDesc": "Keio University Law School JD. AI Governance & Legal Affairs specialist leading regulatory compliance and ethical AI implementation",
    "about.joeDesc": "Waseda University PhD, 15+ years AI research, 12 years investment experience. AI Research specialist driving advanced machine learning and quantitative modeling",
    "about.evyDesc": "University of Tokyo graduate, 5+ years trading experience. Trading systems expert specializing in high-frequency trading infrastructure",
    "about.teamExpertise": "Team Expertise",
    "about.companyInfo": "Company Information",
    "about.companyCapital": "Company Capital",
    "about.assetsUnderManagement": "Assets Under Management",
    "about.assetsAmount": "Over ¥100 million JPY",
    "about.assetsDescription": "We manage over ¥100 million JPY across both internal and client portfolios, leveraging our AI system to ensure precise, adaptive financial strategies.",
    "about.officeAddress": "Office Address",
    "about.ctaTitle": "Ready to Transform Your Financial Operations?",
    "about.ctaDescription": "Discover how our AI-powered solutions can optimize your trading strategies and risk management processes.",
    "about.contactTeam": "Contact Our Team",
    "about.aiGovernance": "AI Governance",
    "about.aiGovernanceDesc": "Regulatory compliance and ethical AI implementation",
    "about.aiGovernanceExpertise": "Risk Assessment, Compliance Automation",
    "about.aiResearch": "AI Research",
    "about.aiResearchDesc": "Advanced machine learning and quantitative modeling",
    "about.aiResearchExpertise": "Neural Networks, Deep Learning, Pattern Recognition",
    "about.tradingSystems": "Trading Systems",
    "about.tradingSystemsDesc": "High-frequency and algorithmic trading infrastructure",
    "about.tradingSystemsExpertise": "Market Making, Portfolio Optimization, Risk Management",
    "about.keyExpertise": "Key Expertise",
    "about.innovation": "Innovation",
    "about.innovationDesc": "Pioneering next-generation AI solutions for financial markets",
    "about.precision": "Precision",
    "about.precisionDesc": "Mathematical rigor and data-driven decision making",
    "about.reliability": "Reliability",
    "about.reliabilityDesc": "Enterprise-grade systems built for 24/7 market operations",

    // Contact Page
    "contact.title": "Get in Touch",
    "contact.subtitle": "Ready to revolutionize your trading strategies with AI? Let's discuss how SAIL Lab can drive your financial innovation forward",
    "contact.sendMessage": "Send us a Message",
    "contact.formDescription": "We'd love to hear about your project and discuss how our AI solutions can help",
    "contact.nameField": "Name",
    "contact.emailField": "Email",
    "contact.companyField": "Company",
    "contact.subjectField": "Subject",
    "contact.messageField": "Message",
    "contact.nameRequired": "Name is required",
    "contact.emailRequired": "Email is required",
    "contact.emailInvalid": "Please enter a valid email address",
    "contact.subjectRequired": "Subject is required",
    "contact.messageRequired": "Message is required",
    "contact.namePlaceholder": "Your full name",
    "contact.emailPlaceholder": "your.email@company.com",
    "contact.companyPlaceholder": "Your company name",
    "contact.subjectPlaceholder": "What can we help you with?",
    "contact.messagePlaceholder": "Tell us more about your project, goals, and how we can help...",
    "contact.sending": "Sending...",
    "contact.sendMessage": "Send Message",
    "contact.tokyoOffice": "Tokyo Office",
    "contact.officeDescription": "Visit us at our headquarters",
    "contact.location": "Location",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.businessHours": "Business Hours",
    "contact.businessDays": "Monday - Friday",
    "contact.businessTime": "9:00 AM - 6:00 PM JST",
    "contact.meetTeam": "Meet Our Leadership Team",
    "contact.contactAction": "Contact",
    "contact.quickResponse": "Quick Response",
    "contact.responseInfo": "We typically respond to inquiries within 24 hours during business days. For urgent matters, please call our office directly.",
    "contact.otherWays": "Other Ways to Connect",
    "contact.linkedin": "LinkedIn",
    "contact.github": "GitHub",
    "contact.twitter": "Twitter",
    "contact.successMessage": "Thank you for your message! We'll get back to you soon.",

    // Blog Page
    "blog.title": "Latest News",
    "blog.subtitle": "Stay updated with the latest news, insights, and developments in AI-powered financial technology and quantitative trading",
    "blog.featured": "Featured",
    "blog.readArticle": "Read Article",
    "blog.neverMiss": "Never Miss an Update",
    "blog.newsletterDesc": "Subscribe to our newsletter for the latest insights in AI trading, market analysis, and financial technology innovations",
    "blog.subscribe": "Subscribe to Newsletter",
    "blog.categoryAll": "All",
    "blog.categoryCompany": "Company News",
    "blog.categoryMarket": "Market News",
    "blog.categoryAnalysis": "Market Analysis",
    "blog.categoryTechnology": "Technology News",
    "blog.categoryIndustry": "Industry News",
    "blog.categoryResearch": "Research News",

    // Insights Page
    "insights.title": "AI Trading Insights",
    "insights.subtitle": "Thought leadership and cutting-edge research in artificial intelligence applications for financial markets and quantitative trading",
    "insights.featured": "Featured",
    "insights.readMore": "Read More",
    "insights.readArticle": "Read Article",
    "insights.stayUpdated": "Stay Updated with Our Research",
    "insights.subscribeDesc": "Subscribe to receive the latest insights in AI-powered trading strategies and financial technology innovations",
    "insights.subscribe": "Subscribe to Newsletter",
    "insights.categoryAll": "All",
    "insights.categoryAI": "AI Trading",
    "insights.categoryDeep": "Deep Learning",
    "insights.categoryGovernance": "AI Governance",
    "insights.categoryNLP": "NLP",
    "insights.categoryRisk": "Risk Management",
    "insights.categoryExplainable": "Explainable AI",

    // AI Agent Quant Myth Article
    "insights.aiAgentMyth.title": "AI Agent Quant Research: A Reality Check",
    "insights.aiAgentMyth.description": "We ran a controlled experiment with QuantaAlpha: Alpha158 baseline vs LLM factor mining vs evolution. The backtest results offer a sobering perspective.",
    "insights.aiAgentMyth.badgeCritical": "Opinion",
    "insights.aiAgentMyth.lead": "Academic AI Agent papers abound: LLM auto factor mining, evolutionary strategies, multi-agent collaboration... We replicated the experiments. Here's what we found.",
    "insights.aiAgentMyth.sectionDesign": "Experiment Design",
    "insights.aiAgentMyth.designText": "Using QuantaAlpha, CSI300 market, 2022 out-of-sample backtest. Three groups: Blue line Alpha158 baseline (20 factors, no mining) | Orange line QuantaAlpha without evolution | Green line QuantaAlpha with evolution (Dir=2, Rounds=3)",
    "insights.aiAgentMyth.sectionData": "What the Data Shows",
    "insights.aiAgentMyth.dataSource": "From batch_summary.json + cumulative excess CSVs (2022-01-04 to 2022-12-30, vs CSI300 benchmark):",
    "insights.aiAgentMyth.dataRow1": "alpha158_20 (baseline, 20 factors, no mining)",
    "insights.aiAgentMyth.dataRow2": "combined_fresh_exp2 (QuantaAlpha seed, no evolution)",
    "insights.aiAgentMyth.dataRow3": "combined_fresh_exp4 (QuantaAlpha with evolution, Dir=2 Rounds=3)",
    "insights.aiAgentMyth.dataColExperiment": "Experiment",
    "insights.aiAgentMyth.dataColReturn": "Cum. excess return",
    "insights.aiAgentMyth.dataColMaxDD": "Max drawdown",
    "insights.aiAgentMyth.dataColRankIC": "Rank IC",
    "insights.aiAgentMyth.dataVal1": "+13.69%",
    "insights.aiAgentMyth.dataVal2": "-0.78%",
    "insights.aiAgentMyth.dataVal3": "-1.13%",
    "insights.aiAgentMyth.dataDD1": "-9.20%",
    "insights.aiAgentMyth.dataDD2": "-7.11%",
    "insights.aiAgentMyth.dataDD3": "-11.54%",
    "insights.aiAgentMyth.dataIC1": "0.0325",
    "insights.aiAgentMyth.dataIC2": "—",
    "insights.aiAgentMyth.dataIC3": "—",
    "insights.aiAgentMyth.dataText2": "In other words: spending substantial compute on LLM mining and evolution did not beat 20 classic price-volume factors in this experiment.",
    "insights.aiAgentMyth.sectionReflect": "A Few Reflections",
    "insights.aiAgentMyth.reflectText1": "We're not dismissing AI Agents—there's real potential. But many papers have experimental design that doesn't hold up under scrutiny: cherry-picked periods, weak baselines, no replication after publication—this kind of 'serious nonsense' is common in top venues.",
    "insights.aiAgentMyth.reflectText2": "In quant, we fear nothing more than self-delusion. A strategy that makes money is what matters. Can Agents help? Perhaps. But show us real backtest results first—don't hide behind fancy frameworks.",
    "insights.aiAgentMyth.footer": "SAIL Lab · Data first, conclusions second",
    "insights.aiAgentMyth.date": "March 2026",
    "insights.aiAgentMyth.readTime": "4 min read",

    // ML Continuous Learning / DeepAgent FX Article
    "insights.mlContinuousLearning.title": "ML Filter vs Baseline: Why Continuous Learning Matters on XAUUSD",
    "insights.mlContinuousLearning.description": "DeepAgent FX live on MQL5 and GogoJungle. Real XAUUSD account: +$1,113 in ~3 trading days. AI ensemble filter vs baseline, pipeline and continuous retraining loop.",
    "insights.mlContinuousLearning.badgeContinuous": "Continuous Learning",
    "insights.mlContinuousLearning.launchLabel": "Product Launch",
    "insights.mlContinuousLearning.launchText": "This month we started selling our newly developed EA — DeepAgent FX — on the MQL5 Market and GogoJungle. No Martingale, no hedging: a next-generation FX AI agent trained on large-scale market data.",
    "insights.mlContinuousLearning.differentiatorText": "What sets DeepAgent FX apart from thousands of other EAs? AI does the filtering. Every candidate trade from our trend engine must pass an ensemble of machine learning models before execution. Below is what that filter actually changes in practice.",
    "insights.mlContinuousLearning.lead": "DeepAgent FX is now live on real accounts. The AI ensemble filter sits between our trend engine and execution — rejecting low-quality setups and keeping only trades the models believe in. Below: live results, then why the filter matters.",
    "insights.mlContinuousLearning.date": "March 2026",
    "insights.mlContinuousLearning.readTime": "12 min read",
    "insights.mlContinuousLearning.sectionLiveTrading": "Live Trading: DeepAgent FX on XAUUSD",
    "insights.mlContinuousLearning.sectionLiveTradingDesc": "Real MT5 account — not a backtest. Deposit $1,456.57 (Jun 22) → balance $2,570.17 (Jun 26). Net profit +$1,113.60 (+76.45%) in roughly three trading days. No Martingale, no hedging.",
    "insights.mlContinuousLearning.liveImageCaption": "MT5 mobile trade history — XAUUSD, Jun 22–26, 2026",
    "insights.mlContinuousLearning.liveStatDeposit": "Initial deposit",
    "insights.mlContinuousLearning.liveStatBalance": "Balance",
    "insights.mlContinuousLearning.liveStatProfit": "Net profit",
    "insights.mlContinuousLearning.liveStatGrowth": "Growth",
    "insights.mlContinuousLearning.liveNote": "Results shown are from our internal research build, which retrains the AI model every ~3 days. The marketplace version ships with a fixed model; see our forward-test panel for ongoing live performance.",
    "insights.mlContinuousLearning.sectionComparison": "Why the AI Filter Matters",
    "insights.mlContinuousLearning.sectionComparisonDesc": "Same trend strategy with AI ensemble filter ON vs OFF — the filter is what turns rule-based signals into selective, higher-quality trades.",
    "insights.mlContinuousLearning.colMetric": "Metric",
    "insights.mlContinuousLearning.colML": "With AI filter",
    "insights.mlContinuousLearning.colBaseline": "Without AI filter",
    "insights.mlContinuousLearning.colDelta": "Δ",
    "insights.mlContinuousLearning.metricProfit": "Net Profit",
    "insights.mlContinuousLearning.metricTrades": "Total Trades",
    "insights.mlContinuousLearning.metricPF": "Profit Factor",
    "insights.mlContinuousLearning.metricPayoff": "Expected Payoff",
    "insights.mlContinuousLearning.metricDD": "Drawdown %",
    "insights.mlContinuousLearning.metricRecovery": "Recovery Factor",
    "insights.mlContinuousLearning.metricSharpe": "Sharpe Ratio",
    "insights.mlContinuousLearning.cardSelectivityTitle": "Selectivity",
    "insights.mlContinuousLearning.cardSelectivityDesc": "ML rejected low-quality setups. Fewer trades, higher edge per trade.",
    "insights.mlContinuousLearning.cardRiskTitle": "Risk",
    "insights.mlContinuousLearning.cardRiskDesc": "Drawdown fell from 32.5% to 21.8%. Recovery factor 5.55 vs 0.58.",
    "insights.mlContinuousLearning.cardConsistencyTitle": "Consistency",
    "insights.mlContinuousLearning.cardConsistencyDesc": "Sharpe 15.81 vs 2.35 — smoother equity curve, not just higher return.",
    "insights.mlContinuousLearning.sectionPipeline": "DeepAgent FX Pipeline: Where ML Fits In",
    "insights.mlContinuousLearning.sectionPipelineDesc": "Rule-based trend engine generates candidates → AI ensemble filters → confidence scoring → dynamic sizing → MT5 execution → feedback loop",
    "insights.mlContinuousLearning.sectionStages": "Six Stages: From Data to Live Trade",
    "insights.mlContinuousLearning.stage1Title": "① Market Data",
    "insights.mlContinuousLearning.stage1Desc": "Millions of M5 bars + tick data. Price, trend, volatility, regime, volume.",
    "insights.mlContinuousLearning.stage2Title": "② Trend Policy Engine",
    "insights.mlContinuousLearning.stage2Desc": "EMA pullback rules — the baseline strategy (no ML yet).",
    "insights.mlContinuousLearning.stage3Title": "③ AI Ensemble Filter",
    "insights.mlContinuousLearning.stage3Desc": "Random Forest, XGBoost, CatBoost, Logistic Regression + calibrated consensus.",
    "insights.mlContinuousLearning.stage4Title": "④ Confidence Scoring",
    "insights.mlContinuousLearning.stage4Desc": "Side-specific thresholds (e.g. Long 0.32 / Short 0.28). Reject weak signals.",
    "insights.mlContinuousLearning.stage5Title": "⑤ Dynamic Position Sizing",
    "insights.mlContinuousLearning.stage5Desc": "Lot multiplier scales with model confidence (1x–3x).",
    "insights.mlContinuousLearning.stage6Title": "⑥ MT5 Live Execution",
    "insights.mlContinuousLearning.stage6Desc": "ONNX models embedded in EA. Trailing stops + session risk rules.",
    "insights.mlContinuousLearning.sectionContinuous": "Why Continuous Learning Is Non-Negotiable",
    "insights.mlContinuousLearning.continuousP1": "A static ML model is a snapshot of the past. Gold regimes shift — volatility clusters change, session dynamics evolve, macro events rewrite correlation structures. The baseline strategy (Pass 0) has no mechanism to adapt; it fires every rule-based signal regardless of current market quality.",
    "insights.mlContinuousLearning.loopTitle": "Our Continuous Learning Loop",
    "insights.mlContinuousLearning.loop1": "Batch backtest — collect every trade + 20 features at entry",
    "insights.mlContinuousLearning.loop2": "Walk-forward selection — pick best model on out-of-sample 30%",
    "insights.mlContinuousLearning.loop3": "Full-data refit — retrain deployment copy on 100% recent window (aligned Python + MT5 ONNX)",
    "insights.mlContinuousLearning.loop4": "Side-specific deploy — separate Long/Short models + thresholds to MT5 EA",
    "insights.mlContinuousLearning.loop5": "Performance feedback — live results feed next batch cycle (target: retrain every ~3 days)",
    "insights.mlContinuousLearning.keyInsightTitle": "Key insight",
    "insights.mlContinuousLearning.keyInsightText": "The ML advantage in Pass 1 is not magic — it is learned selectivity from recent trade outcomes. Without continuous retraining, that edge decays. With it, the filter stays calibrated to the market you are actually trading today.",
    "insights.mlContinuousLearning.sectionTakeaways": "Takeaways",
    "insights.mlContinuousLearning.takeaway1": "ML does not replace the trend strategy — it filters it.",
    "insights.mlContinuousLearning.takeaway2": "Same rules, 3× profit, half the trades, one-third less drawdown.",
    "insights.mlContinuousLearning.takeaway3": "Side-specific models (Long ≠ Short) outperform a single common threshold.",
    "insights.mlContinuousLearning.takeaway4": "Continuous learning closes the loop: live → data → retrain → redeploy → live.",
    "insights.mlContinuousLearning.takeaway5": "Python live filter and MT5 ONNX EA share identical decision logic.",
    "insights.mlContinuousLearning.footer": "SAIL Lab · Tokyo · AI × Data × Strategy × Risk Management",
    "insights.mlContinuousLearning.backLink": "← Back to Insights",
    "insights.mlContinuousLearning.linkMql5": "MQL5 Market",
    "insights.mlContinuousLearning.linkGogoJungle": "GogoJungle",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.retry": "Retry",
  },
  zh: {
    // Header
    "nav.about": "关于",
    "nav.portfolio": "产品组合",
    "nav.insights": "洞察",
    "nav.blog": "博客",
    "nav.contact": "联系",
    "nav.dashboard": "仪表板",

    // Home page
    "home.title": "AI驱动的\n金融创新",
    "home.subtitle": "为量化系统、投资分析和交易自动化提供革命性AI解决方案",
    "home.contact": "联系我们",
    "home.cta": "开始交易",
    "home.learn": "了解更多",

    // Dashboard
    "dashboard.title": "SAIL实验室仪表板",
    "dashboard.subtitle": "多智能体AI交易系统与实时市场分析",
    "dashboard.agents": "AI智能体在线",
    "dashboard.refresh": "刷新",

    // Portfolio
    "portfolio.title": "我们的产品组合",
    "portfolio.subtitle": "通过创新、自动化和智能决策转变金融服务的综合AI解决方案",
    "portfolio.coreServices": "核心服务",
    "portfolio.customSolutions": "定制AI金融解决方案",
    "portfolio.customDesc": "除了我们的核心产品外，我们还开发针对您特定金融挑战的定制AI解决方案。从合规自动化到定制交易算法，我们的团队提供企业级解决方案。",
    "portfolio.regulatoryAI": "监管AI",
    "portfolio.regulatoryDesc": "自动化合规监控和报告",
    "portfolio.customAlgorithms": "定制算法",
    "portfolio.customAlgDesc": "专有交易策略开发",
    "portfolio.ctaTitle": "准备好加速您的金融AI之旅了吗？",
    "portfolio.ctaDesc": "安排咨询，探索我们的AI解决方案如何转变您的金融运营并推动可持续增长。",
    "portfolio.scheduleConsult": "安排咨询",
    "portfolio.viewPricing": "查看价格详情",
    "portfolio.multiAgentTitle": "Multi LLM Agent based Stock Analysis (In Dashboard)",
    "portfolio.multiAgentCategory": "投资研究",
    "portfolio.multiAgentDesc": "使用协作AI智能体进行投资分析，提供市场洞察和投资报告",
    "portfolio.multiAgentFeature1": "实时市场情绪分析",
    "portfolio.multiAgentFeature2": "多源数据聚合",
    "portfolio.multiAgentFeature3": "自动化研究报告",
    "portfolio.multiAgentFeature4": "风险因素识别",
    "portfolio.multiAgentFeature5": "投资组合优化建议",
    "portfolio.neuralNetworkTitle": "神经网络量化交易 (See Back Test Result in INSIGHTS)",
    "portfolio.neuralNetworkCategory": "交易系统",
    "portfolio.neuralNetworkDesc": "具有实时市场优化功能的自适应神经网络交易系统",
    "portfolio.neuralNetworkFeature1": "深度学习价格预测",
    "portfolio.neuralNetworkFeature2": "自适应策略优化",
    "portfolio.neuralNetworkFeature3": "实时风险管理",
    "portfolio.neuralNetworkFeature4": "多资产类别支持",
    "portfolio.neuralNetworkFeature5": "高频执行",
    "portfolio.communityTitle": "AI交易者社区",
    "portfolio.communityCategory": "平台与教育",
    "portfolio.communityDesc": "连接AI交易者和投资者的平台，提供策略分享和绩效分析",
    "portfolio.communityFeature1": "策略回测环境",
    "portfolio.communityFeature2": "AI模型市场",
    "portfolio.communityFeature3": "教育研讨会",
    "portfolio.communityFeature4": "点对点学习",
    "portfolio.communityFeature5": "绩效分析仪表板",
    "portfolio.keyFeatures": "核心功能",
    "portfolio.popular": "热门",
    "portfolio.enterprise": "企业版",
    "portfolio.beta": "测试版",

    // Terms of Service
    "terms.title": "服务条款",
    "terms.subtitle": "这些服务条款规定了您使用SAIL实验室AI交易平台的条件。请在使用我们的服务前仔细阅读这些条款。",
    "terms.effectiveDate": "生效日期：2025年1月1日",
    "terms.version": "版本 2.0",
    "terms.riskNotice": "重要金融风险提示",
    "terms.highRiskWarning": "高风险投资警告：交易和投资存在重大财务损失风险。",

    // Privacy Policy
    "privacy.title": "隐私政策",
    "privacy.subtitle": "您的隐私对我们很重要。本隐私政策解释了SAIL实验室在您使用我们的AI交易平台时如何收集、使用和保护您的个人信息。",
    "privacy.lastUpdated": "最后更新：2025年1月1日",

    // About Page
    "about.title": "关于SAIL实验室",
    "about.subtitle": "通过先进的AI研究和尖端多智能体系统，引领金融科技的未来",
    "about.mission": "我们的使命",
    "about.missionText1": "我们的核心使命是通过我们专有的基于LLM的多智能体分析引擎，为个人和组织提供前沿的投资组合管理工具。",
    "about.missionText2": "由AI研究人员和金融专家团队开发，我们的技术持续监控和分析全球市场、金融新闻和机构洞察——提供具有人类级理解能力的动态、数据驱动的建议。",
    "about.team": "认识我们的团队",
    "about.ceo": "首席执行官兼创始人",
    "about.ceoDesc": "领导SAIL实验室实现AI金融分析民主化的愿景",
    "about.jayneDesc": "庆应大学法学院法学博士。AI治理与法律事务专家，引领合规和道德AI实施",
    "about.joeDesc": "早稻田大学博士，15年以上AI研究经验，12年投资经验。AI研究专家，推动先进机器学习和量化建模",
    "about.evyDesc": "东京大学毕业，5年以上交易经验。交易系统专家，专长高频交易基础设施",
    "about.teamExpertise": "团队专业技能",
    "about.companyInfo": "公司信息",
    "about.companyCapital": "公司资本",
    "about.assetsUnderManagement": "管理资产规模",
    "about.assetsAmount": "超过1亿日元",
    "about.assetsDescription": "我们管理超过1亿日元的内部和客户投资组合，利用我们的AI系统确保精准、适应性强的金融策略。",
    "about.officeAddress": "办公地址",
    "about.ctaTitle": "准备好转变您的金融业务了吗？",
    "about.ctaDescription": "探索我们的AI解决方案如何优化您的交易策略和风险管理流程。",
    "about.contactTeam": "联系我们的团队",
    "about.aiGovernance": "AI治理",
    "about.aiGovernanceDesc": "合规和道德AI实施",
    "about.aiGovernanceExpertise": "风险评估、合规自动化",
    "about.aiResearch": "AI研究",
    "about.aiResearchDesc": "先进机器学习和量化建模",
    "about.aiResearchExpertise": "神经网络、深度学习、模式识别",
    "about.tradingSystems": "交易系统",
    "about.tradingSystemsDesc": "高频和算法交易基础设施",
    "about.tradingSystemsExpertise": "做市、投资组合优化、风险管理",
    "about.keyExpertise": "核心专长",
    "about.innovation": "创新",
    "about.innovationDesc": "为金融市场开拓下一代AI解决方案",
    "about.precision": "精准",
    "about.precisionDesc": "数学严谨性和数据驱动决策",
    "about.reliability": "可靠性",
    "about.reliabilityDesc": "为7×24小时市场运营构建的企业级系统",

    // Contact Page
    "contact.title": "联系我们",
    "contact.subtitle": "准备好用AI革新您的交易策略了吗？让我们讨论SAIL实验室如何推动您的金融创新发展",
    "contact.sendMessage": "发送消息",
    "contact.formDescription": "我们很乐意了解您的项目，并讨论我们的AI解决方案如何为您提供帮助",
    "contact.nameField": "姓名",
    "contact.emailField": "邮箱",
    "contact.companyField": "公司",
    "contact.subjectField": "主题",
    "contact.messageField": "消息",
    "contact.nameRequired": "姓名为必填项",
    "contact.emailRequired": "邮箱为必填项",
    "contact.emailInvalid": "请输入有效的邮箱地址",
    "contact.subjectRequired": "主题为必填项",
    "contact.messageRequired": "消息为必填项",
    "contact.namePlaceholder": "您的全名",
    "contact.emailPlaceholder": "your.email@company.com",
    "contact.companyPlaceholder": "您的公司名称",
    "contact.subjectPlaceholder": "我们能为您做些什么？",
    "contact.messagePlaceholder": "告诉我们更多关于您的项目、目标以及我们如何提供帮助...",
    "contact.sending": "发送中...",
    "contact.sendMessage": "发送消息",
    "contact.tokyoOffice": "东京办公室",
    "contact.officeDescription": "访问我们的总部",
    "contact.location": "位置",
    "contact.email": "邮箱",
    "contact.phone": "电话",
    "contact.businessHours": "营业时间",
    "contact.businessDays": "周一至周五",
    "contact.businessTime": "上午9:00 - 下午6:00 日本标准时间",
    "contact.meetTeam": "认识我们的领导团队",
    "contact.contactAction": "联系",
    "contact.quickResponse": "快速响应",
    "contact.responseInfo": "我们通常在工作日24小时内回复询问。如有紧急事项，请直接致电我们的办公室。",
    "contact.otherWays": "其他联系方式",
    "contact.linkedin": "领英",
    "contact.github": "GitHub",
    "contact.twitter": "Twitter",
    "contact.successMessage": "感谢您的消息！我们会尽快回复您。",

    // Blog Page
    "blog.title": "最新动态",
    "blog.subtitle": "了解AI金融科技和量化交易领域的最新新闻、见解和发展动态",
    "blog.featured": "精选",
    "blog.readArticle": "阅读文章",
    "blog.neverMiss": "不错过任何更新",
    "blog.newsletterDesc": "订阅我们的新闻通讯，获取AI交易、市场分析和金融科技创新的最新见解",
    "blog.subscribe": "订阅新闻通讯",
    "blog.categoryAll": "全部",
    "blog.categoryCompany": "公司新闻",
    "blog.categoryMarket": "市场新闻",
    "blog.categoryAnalysis": "市场分析",
    "blog.categoryTechnology": "技术新闻",
    "blog.categoryIndustry": "行业新闻",
    "blog.categoryResearch": "研究新闻",

    // Insights Page
    "insights.title": "AI交易洞察",
    "insights.subtitle": "人工智能在金融市场和量化交易应用中的思想领导力和前沿研究",
    "insights.featured": "精选",
    "insights.readMore": "阅读更多",
    "insights.readArticle": "阅读文章",
    "insights.stayUpdated": "获取我们的最新研究",
    "insights.subscribeDesc": "订阅以接收AI交易策略和金融科技创新的最新见解",
    "insights.subscribe": "订阅新闻通讯",
    "insights.categoryAll": "全部",
    "insights.categoryAI": "AI交易",
    "insights.categoryDeep": "深度学习",
    "insights.categoryGovernance": "AI治理",
    "insights.categoryNLP": "自然语言处理",
    "insights.categoryRisk": "风险管理",
    "insights.categoryExplainable": "可解释AI",

    // AI Agent Quant Myth Article
    "insights.aiAgentMyth.title": "AI Agent 量化研究：一次冷静的对照实验",
    "insights.aiAgentMyth.description": "我们用 QuantaAlpha 做了对照实验：Alpha158 基线 vs LLM 因子挖掘 vs 进化策略。回测结果值得思考。",
    "insights.aiAgentMyth.badgeCritical": "观点",
    "insights.aiAgentMyth.lead": "学术圈 AI Agent 论文不少：LLM 自动挖掘因子、进化策略、多智能体协作……我们照着做了实验，来看看结果。",
    "insights.aiAgentMyth.sectionDesign": "实验设计",
    "insights.aiAgentMyth.designText": "使用 QuantaAlpha 框架，CSI300 市场，2022 年样本外回测。对比三组：蓝线 Alpha158 基线（20 因子，不挖掘）｜橙线 QuantaAlpha 无进化｜绿线 QuantaAlpha 进化版（Dir=2, Rounds=3）",
    "insights.aiAgentMyth.sectionData": "数据说话",
    "insights.aiAgentMyth.dataSource": "数据来自 batch_summary.json 及累计超额收益 CSV（2022-01-04 至 2022-12-30，相对 CSI300 基准）：",
    "insights.aiAgentMyth.dataRow1": "alpha158_20（基线，20 因子，不挖掘）",
    "insights.aiAgentMyth.dataRow2": "combined_fresh_exp2（QuantaAlpha 种子，无进化）",
    "insights.aiAgentMyth.dataRow3": "combined_fresh_exp4（QuantaAlpha 进化版，Dir=2 Rounds=3）",
    "insights.aiAgentMyth.dataColExperiment": "实验",
    "insights.aiAgentMyth.dataColReturn": "累计超额收益",
    "insights.aiAgentMyth.dataColMaxDD": "最大回撤",
    "insights.aiAgentMyth.dataColRankIC": "Rank IC",
    "insights.aiAgentMyth.dataDD1": "-9.20%",
    "insights.aiAgentMyth.dataDD2": "-7.11%",
    "insights.aiAgentMyth.dataDD3": "-11.54%",
    "insights.aiAgentMyth.dataIC1": "0.0325",
    "insights.aiAgentMyth.dataIC2": "—",
    "insights.aiAgentMyth.dataIC3": "—",
    "insights.aiAgentMyth.dataVal1": "+13.69%",
    "insights.aiAgentMyth.dataVal2": "-0.78%",
    "insights.aiAgentMyth.dataVal3": "-1.13%",
    "insights.aiAgentMyth.dataText2": "也就是说：在本实验中，投入大量算力做 LLM 挖掘与进化，并未超越 20 个经典量价因子。",
    "insights.aiAgentMyth.sectionReflect": "一点思考",
    "insights.aiAgentMyth.reflectText1": "我们并非否定 AI Agent 的价值——潜力是有的。但很多论文的实验设计经不起推敲：cherry-pick 的区间、不 rigorous 的 baseline、发完就不管复现——这种「一本正经胡说八道」在顶会里并不少见。",
    "insights.aiAgentMyth.reflectText2": "做量化的人，最怕的就是自嗨。策略能赚钱才是硬道理。Agent 能帮上忙吗？也许。但先拿真金白银的回测结果说话，别拿 fancy 的框架糊弄人。",
    "insights.aiAgentMyth.footer": "SAIL Lab · 数据先行，结论其次",
    "insights.aiAgentMyth.date": "2026年3月",
    "insights.aiAgentMyth.readTime": "4 分钟阅读",

    // ML Continuous Learning / DeepAgent FX Article
    "insights.mlContinuousLearning.title": "ML 过滤器 vs 基线：XAUUSD 上持续学习为何重要",
    "insights.mlContinuousLearning.description": "DeepAgent FX 已在 MQL5 与 GogoJungle 上线。XAUUSD 实盘约 3 个交易日盈利 +$1,113。AI 过滤器 vs 基线、流程与持续重训。",
    "insights.mlContinuousLearning.badgeContinuous": "持续学习",
    "insights.mlContinuousLearning.launchLabel": "产品发布",
    "insights.mlContinuousLearning.launchText": "本月我们开始在 MQL5 Market 和 GogoJungle 上销售新开发的 EA — DeepAgent FX。无马丁格尔、无对冲，基于大规模市场数据训练的下一代 FX AI 智能体。",
    "insights.mlContinuousLearning.differentiatorText": "DeepAgent FX 与市场上数千个 EA 最大的不同是什么？AI 负责过滤。趋势引擎生成的每一笔候选交易，都必须先通过机器学习模型集成审核，才会真正下单。下文展示这一过滤器在实际中带来的差异。",
    "insights.mlContinuousLearning.lead": "DeepAgent FX 已在真实账户运行。AI 集成过滤器位于趋势引擎与下单之间 — 拒绝低质量 setup，只保留模型认可的交易。下文：实盘结果，以及过滤器为何重要。",
    "insights.mlContinuousLearning.date": "2026年3月",
    "insights.mlContinuousLearning.readTime": "12 分钟阅读",
    "insights.mlContinuousLearning.sectionLiveTrading": "实盘交易：DeepAgent FX · XAUUSD",
    "insights.mlContinuousLearning.sectionLiveTradingDesc": "真实 MT5 账户 — 非回测。6 月 22 日入金 $1,456.57 → 6 月 26 日余额 $2,570.17。约三个交易日净利润 +$1,113.60（+76.45%）。无马丁格尔、无对冲。",
    "insights.mlContinuousLearning.liveImageCaption": "MT5 手机端成交记录 — XAUUSD，2026.06.22–26",
    "insights.mlContinuousLearning.liveStatDeposit": "初始入金",
    "insights.mlContinuousLearning.liveStatBalance": "账户余额",
    "insights.mlContinuousLearning.liveStatProfit": "净利润",
    "insights.mlContinuousLearning.liveStatGrowth": "增长率",
    "insights.mlContinuousLearning.liveNote": "所示结果为内部研究版（约每 3 天重训 AI 模型）。市场上架版为固定模型；持续表现请参见 forward-test 面板。",
    "insights.mlContinuousLearning.sectionComparison": "AI 过滤器为何重要",
    "insights.mlContinuousLearning.sectionComparisonDesc": "相同趋势策略，AI 集成过滤开启 vs 关闭 — 过滤器将规则信号转化为更高质量、更有选择性的交易。",
    "insights.mlContinuousLearning.colMetric": "指标",
    "insights.mlContinuousLearning.colML": "有 AI 过滤",
    "insights.mlContinuousLearning.colBaseline": "无 AI 过滤",
    "insights.mlContinuousLearning.colDelta": "Δ",
    "insights.mlContinuousLearning.metricProfit": "净利润",
    "insights.mlContinuousLearning.metricTrades": "总交易数",
    "insights.mlContinuousLearning.metricPF": "盈利因子",
    "insights.mlContinuousLearning.metricPayoff": "期望收益",
    "insights.mlContinuousLearning.metricDD": "回撤 %",
    "insights.mlContinuousLearning.metricRecovery": "恢复因子",
    "insights.mlContinuousLearning.metricSharpe": "Sharpe 比率",
    "insights.mlContinuousLearning.cardSelectivityTitle": "选择性",
    "insights.mlContinuousLearning.cardSelectivityDesc": "ML 拒绝低质量 setup。交易更少，单笔 edge 更高。",
    "insights.mlContinuousLearning.cardRiskTitle": "风险",
    "insights.mlContinuousLearning.cardRiskDesc": "回撤从 32.5% 降至 21.8%。恢复因子 5.55 vs 0.58。",
    "insights.mlContinuousLearning.cardConsistencyTitle": "稳定性",
    "insights.mlContinuousLearning.cardConsistencyDesc": "Sharpe 15.81 vs 2.35 — 权益曲线更平滑，不只是更高收益。",
    "insights.mlContinuousLearning.sectionPipeline": "DeepAgent FX 流程：ML 所在位置",
    "insights.mlContinuousLearning.sectionPipelineDesc": "规则趋势引擎生成候选 → AI 集成过滤 → 置信度评分 → 动态仓位 → MT5 执行 → 反馈循环",
    "insights.mlContinuousLearning.sectionStages": "六阶段：从数据到实盘",
    "insights.mlContinuousLearning.stage1Title": "① 市场数据",
    "insights.mlContinuousLearning.stage1Desc": "数百万 M5 K 线 + tick 数据。价格、趋势、波动、regime、成交量。",
    "insights.mlContinuousLearning.stage2Title": "② 趋势策略引擎",
    "insights.mlContinuousLearning.stage2Desc": "EMA 回撤规则 — 基线策略（尚未接入 ML）。",
    "insights.mlContinuousLearning.stage3Title": "③ AI 集成过滤",
    "insights.mlContinuousLearning.stage3Desc": "Random Forest、XGBoost、CatBoost、Logistic Regression + 校准共识。",
    "insights.mlContinuousLearning.stage4Title": "④ 交易置信度评分",
    "insights.mlContinuousLearning.stage4Desc": "方向专属阈值（如 Long 0.32 / Short 0.28）。拒绝弱信号。",
    "insights.mlContinuousLearning.stage5Title": "⑤ 动态仓位管理",
    "insights.mlContinuousLearning.stage5Desc": "手数乘数随模型置信度调整（1x–3x）。",
    "insights.mlContinuousLearning.stage6Title": "⑥ MT5 实盘执行",
    "insights.mlContinuousLearning.stage6Desc": "ONNX 模型嵌入 EA。移动止损 + 时段风控。",
    "insights.mlContinuousLearning.sectionContinuous": "为什么持续学习不可或缺",
    "insights.mlContinuousLearning.continuousP1": "静态 ML 模型只是过去的快照。黄金 regime 会变 — 波动聚集、时段结构、宏观事件都会改写相关性。基线策略（Pass 0）没有适应机制，无论当前市场质量如何都会触发每一条规则信号。",
    "insights.mlContinuousLearning.loopTitle": "我们的持续学习循环",
    "insights.mlContinuousLearning.loop1": "批量回测 — 收集每笔交易及 20 个入场特征",
    "insights.mlContinuousLearning.loop2": "Walk-forward 选模 — 在 30% 样本外数据上选最优模型",
    "insights.mlContinuousLearning.loop3": "全量 refit — 在 100% 近期窗口重训部署模型（Python 与 MT5 ONNX 对齐）",
    "insights.mlContinuousLearning.loop4": "方向专属部署 — Long/Short 独立模型与阈值同步至 MT5 EA",
    "insights.mlContinuousLearning.loop5": "绩效反馈 — 实盘结果进入下一批训练周期（目标：约每 3 天重训）",
    "insights.mlContinuousLearning.keyInsightTitle": "要点",
    "insights.mlContinuousLearning.keyInsightText": "Pass 1 的 ML 优势并非魔法 — 而是来自近期交易结果的学习选择性。没有持续重训，edge 会衰减；有了它，过滤器才能校准到你今天实际交易的市场。",
    "insights.mlContinuousLearning.sectionTakeaways": "总结",
    "insights.mlContinuousLearning.takeaway1": "ML 不替代趋势策略 — 它过滤策略。",
    "insights.mlContinuousLearning.takeaway2": "相同规则下：3 倍利润、一半交易数、回撤降低约三分之一。",
    "insights.mlContinuousLearning.takeaway3": "方向专属模型（Long ≠ Short）优于单一共用阈值。",
    "insights.mlContinuousLearning.takeaway4": "持续学习闭合循环：实盘 → 数据 → 重训 → 部署 → 实盘。",
    "insights.mlContinuousLearning.takeaway5": "Python 实盘过滤器与 MT5 ONNX EA 共享相同决策逻辑。",
    "insights.mlContinuousLearning.footer": "SAIL Lab · 东京 · AI × 数据 × 策略 × 风险管理",
    "insights.mlContinuousLearning.backLink": "← 返回 Insights",
    "insights.mlContinuousLearning.linkMql5": "MQL5 Market",
    "insights.mlContinuousLearning.linkGogoJungle": "GogoJungle",

    // Common
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.retry": "重试",
  },
  ja: {
    // Header
    "nav.about": "アバウト",
    "nav.portfolio": "ポートフォリオ",
    "nav.insights": "インサイト",
    "nav.blog": "ブログ",
    "nav.contact": "コンタクト",
    "nav.dashboard": "ダッシュボード",

    // Home page
    "home.title": "AI駆動\n金融イノベーション",
    "home.subtitle": "クオンツシステム、投資分析、取引自動化のための革新的AIソリューション",
    "home.contact": "お問い合わせ",
    "home.cta": "取引開始",
    "home.learn": "詳細を見る",

    // Dashboard
    "dashboard.title": "SAILラボダッシュボード",
    "dashboard.subtitle": "マルチエージェントAI取引システム・リアルタイム市場分析",
    "dashboard.agents": "AIエージェントオンライン",
    "dashboard.refresh": "更新",

    // Portfolio
    "portfolio.title": "ポートフォリオ",
    "portfolio.subtitle": "革新、自動化、インテリジェント意思決定を通じて金融サービスを変革する包括的AIソリューション",
    "portfolio.coreServices": "コアサービス",
    "portfolio.customSolutions": "カスタムAI金融ソリューション",
    "portfolio.customDesc": "コア製品に加えて、お客様固有の金融課題に合わせたカスタムAIソリューションを開発しています。規制遵守の自動化からカスタム取引アルゴリズムまで、当社チームがエンタープライズグレードのソリューションを提供します。",
    "portfolio.regulatoryAI": "規制AI",
    "portfolio.regulatoryDesc": "自動化されたコンプライアンス監視とレポート",
    "portfolio.customAlgorithms": "カスタムアルゴリズム",
    "portfolio.customAlgDesc": "独自取引戦略開発",
    "portfolio.ctaTitle": "金融AIジャーニーを加速する準備はできていますか？",
    "portfolio.ctaDesc": "当社のAIソリューションがお客様の金融業務をどのように変革し、持続可能な成長を促進できるかを探るためのコンサルテーションをスケジュールしてください。",
    "portfolio.scheduleConsult": "コンサルテーション予約",
    "portfolio.viewPricing": "価格詳細を見る",
    "portfolio.multiAgentTitle": "Multi LLM Agent based Stock Analysis (In Dashboard)",
    "portfolio.multiAgentCategory": "投資リサーチ",
    "portfolio.multiAgentDesc": "協調AIエージェントを使用した投資分析、市場洞察と投資レポートの提供",
    "portfolio.multiAgentFeature1": "リアルタイム市場センチメント分析",
    "portfolio.multiAgentFeature2": "マルチソースデータ集約",
    "portfolio.multiAgentFeature3": "自動化されたリサーチレポート",
    "portfolio.multiAgentFeature4": "リスクファクター識別",
    "portfolio.multiAgentFeature5": "ポートフォリオ最適化推奨",
    "portfolio.neuralNetworkTitle": "ニューラルネットワーク量的取引 (See Back Test Result in INSIGHTS)",
    "portfolio.neuralNetworkCategory": "取引システム",
    "portfolio.neuralNetworkDesc": "リアルタイム市場最適化を備えた適応型ニューラルネットワーク取引システム",
    "portfolio.neuralNetworkFeature1": "ディープラーニング価格予測",
    "portfolio.neuralNetworkFeature2": "適応型戦略最適化",
    "portfolio.neuralNetworkFeature3": "リアルタイムリスク管理",
    "portfolio.neuralNetworkFeature4": "マルチアセットクラスサポート",
    "portfolio.neuralNetworkFeature5": "高頻度実行",
    "portfolio.communityTitle": "AIトレーダーコミュニティ",
    "portfolio.communityCategory": "プラットフォーム・教育",
    "portfolio.communityDesc": "AIトレーダーと投資家を結ぶプラットフォーム、戦略共有とパフォーマンス分析",
    "portfolio.communityFeature1": "戦略バックテスト環境",
    "portfolio.communityFeature2": "AIモデルマーケットプレイス",
    "portfolio.communityFeature3": "教育ワークショップ",
    "portfolio.communityFeature4": "ピアツーピア学習",
    "portfolio.communityFeature5": "パフォーマンス分析ダッシュボード",
    "portfolio.keyFeatures": "主要機能",
    "portfolio.popular": "人気",
    "portfolio.enterprise": "エンタープライズ",
    "portfolio.beta": "ベータ",

    // Terms of Service
    "terms.title": "利用規約",
    "terms.subtitle": "この利用規約は、SAIL LabのAI取引プラットフォームの使用を規定します。当社のサービスを使用する前に、これらの規約を注意深くお読みください。",
    "terms.effectiveDate": "発効日：2025年1月1日",
    "terms.version": "バージョン 2.0",
    "terms.riskNotice": "重要な金融リスク通知",
    "terms.highRiskWarning": "高リスク投資警告：取引と投資には重大な財務損失のリスクが伴います。",

    // Privacy Policy
    "privacy.title": "プライバシーポリシー",
    "privacy.subtitle": "お客様のプライバシーは当社にとって重要です。このプライバシーポリシーは、SAIL Labが当社のAI取引プラットフォームを使用する際にお客様の個人情報をどのように収集、使用、保護するかを説明しています。",
    "privacy.lastUpdated": "最終更新：2025年1月1日",

    // About Page
    "about.title": "SAIL Labについて",
    "about.subtitle": "先進的なAI研究と最先端のマルチエージェントシステムを通じて、金融テクノロジーの未来を切り開く",
    "about.mission": "私たちのミッション",
    "about.missionText1": "私たちの中核的使命は、独自のLLMベースのマルチエージェント分析エンジンによって、個人と組織に最先端のポートフォリオ管理ツールを提供することです。",
    "about.missionText2": "AI研究者と金融専門家のチームによって開発された当社の技術は、グローバル市場、金融ニュース、機関投資家の洞察を継続的に監視・分析し、人間レベルの理解力を持つ動的でデータ駆動型の推奨事項を提供します。",
    "about.team": "チームの紹介",
    "about.ceo": "CEO兼創設者",
    "about.ceoDesc": "AI金融分析の民主化というSAIL Labのビジョンをリード",
    "about.jayneDesc": "慶應義塾大学法科大学院法務博士。AIガバナンス・法務専門家として規制遵守と倫理的AI実装をリード",
    "about.joeDesc": "早稲田大学博士号、15年以上のAI研究経験、12年の投資経験。先進的機械学習と量的モデリングを推進するAI研究専門家",
    "about.evyDesc": "東京大学卒業、5年以上の取引経験。高頻度取引インフラを専門とする取引システム専門家",
    "about.teamExpertise": "チーム専門分野",
    "about.companyInfo": "会社情報",
    "about.companyCapital": "会社資本金",
    "about.assetsUnderManagement": "運用資産",
    "about.assetsAmount": "1億円以上",
    "about.assetsDescription": "当社は内部およびクライアントのポートフォリオで1億円以上を運用し、AIシステムを活用して精密で適応性の高い金融戦略を確保しています。",
    "about.officeAddress": "オフィス所在地",
    "about.ctaTitle": "金融業務の変革の準備はできていますか？",
    "about.ctaDescription": "当社のAIソリューションがお客様の取引戦略とリスク管理プロセスをどのように最適化できるかをご覧ください。",
    "about.contactTeam": "チームにお問い合わせ",
    "about.aiGovernance": "AIガバナンス",
    "about.aiGovernanceDesc": "規制遵守と倫理的AI実装",
    "about.aiGovernanceExpertise": "リスク評価、コンプライアンス自動化",
    "about.aiResearch": "AI研究",
    "about.aiResearchDesc": "先進的機械学習と量的モデリング",
    "about.aiResearchExpertise": "ニューラルネットワーク、ディープラーニング、パターン認識",
    "about.tradingSystems": "取引システム",
    "about.tradingSystemsDesc": "高頻度・アルゴリズム取引インフラ",
    "about.tradingSystemsExpertise": "マーケットメイキング、ポートフォリオ最適化、リスク管理",
    "about.keyExpertise": "主要専門分野",
    "about.innovation": "イノベーション",
    "about.innovationDesc": "金融市場向け次世代AIソリューションの開拓",
    "about.precision": "精密性",
    "about.precisionDesc": "数学的厳密性とデータ駆動意思決定",
    "about.reliability": "信頼性",
    "about.reliabilityDesc": "24時間市場運営向けエンタープライズグレードシステム",

    // Contact Page
    "contact.title": "お問い合わせ",
    "contact.subtitle": "AIで取引戦略を革新する準備はできていますか？SAIL Labがお客様の金融イノベーションをどのように推進できるかを話し合いましょう",
    "contact.sendMessage": "メッセージを送信",
    "contact.formDescription": "お客様のプロジェクトについてお聞かせいただき、当社のAIソリューションがどのようにお役に立てるかを話し合いたいと思います",
    "contact.nameField": "お名前",
    "contact.emailField": "メールアドレス",
    "contact.companyField": "会社名",
    "contact.subjectField": "件名",
    "contact.messageField": "メッセージ",
    "contact.nameRequired": "お名前は必須です",
    "contact.emailRequired": "メールアドレスは必須です",
    "contact.emailInvalid": "有効なメールアドレスを入力してください",
    "contact.subjectRequired": "件名は必須です",
    "contact.messageRequired": "メッセージは必須です",
    "contact.namePlaceholder": "お名前をフルネームで",
    "contact.emailPlaceholder": "your.email@company.com",
    "contact.companyPlaceholder": "会社名",
    "contact.subjectPlaceholder": "どのようなご相談でしょうか？",
    "contact.messagePlaceholder": "プロジェクト、目標、当社がどのようにお役に立てるかについて詳しくお聞かせください...",
    "contact.sending": "送信中...",
    "contact.sendMessage": "メッセージを送信",
    "contact.tokyoOffice": "東京オフィス",
    "contact.officeDescription": "本社をご訪問ください",
    "contact.location": "所在地",
    "contact.email": "メール",
    "contact.phone": "電話",
    "contact.businessHours": "営業時間",
    "contact.businessDays": "月曜日～金曜日",
    "contact.businessTime": "午前9:00 - 午後6:00 日本標準時",
    "contact.meetTeam": "リーダーシップチームの紹介",
    "contact.contactAction": "お問い合わせ",
    "contact.quickResponse": "迅速な対応",
    "contact.responseInfo": "営業日は通常24時間以内にお問い合わせにお答えしています。緊急の場合は、オフィスまで直接お電話ください。",
    "contact.otherWays": "その他の連絡方法",
    "contact.linkedin": "LinkedIn",
    "contact.github": "GitHub",
    "contact.twitter": "Twitter",
    "contact.successMessage": "お問い合わせありがとうございます！すぐに返信いたします。",

    // Blog Page
    "blog.title": "最新ニュース",
    "blog.subtitle": "AI金融テクノロジーと量的取引の最新ニュース、洞察、開発動向をお届けします",
    "blog.featured": "注目記事",
    "blog.readArticle": "記事を読む",
    "blog.neverMiss": "最新情報をお見逃しなく",
    "blog.newsletterDesc": "AIトレーディング、市場分析、金融テクノロジー革新の最新洞察をニュースレターでお届けします",
    "blog.subscribe": "ニュースレターを購読",
    "blog.categoryAll": "すべて",
    "blog.categoryCompany": "企業ニュース",
    "blog.categoryMarket": "市場ニュース",
    "blog.categoryAnalysis": "市場分析",
    "blog.categoryTechnology": "技術ニュース",
    "blog.categoryIndustry": "業界ニュース",
    "blog.categoryResearch": "研究ニュース",

    // Insights Page
    "insights.title": "AIトレーディング洞察",
    "insights.subtitle": "金融市場と量的取引における人工知能アプリケーションの思想的リーダーシップと最先端研究",
    "insights.featured": "注目記事",
    "insights.readMore": "続きを読む",
    "insights.readArticle": "記事を読む",
    "insights.stayUpdated": "最新の研究情報をお届け",
    "insights.subscribeDesc": "AI取引戦略と金融テクノロジーイノベーションの最新洞察を受け取るための購読",
    "insights.subscribe": "ニュースレターを購読",
    "insights.categoryAll": "すべて",
    "insights.categoryAI": "AIトレーディング",
    "insights.categoryDeep": "ディープラーニング",
    "insights.categoryGovernance": "AIガバナンス",
    "insights.categoryNLP": "自然言語処理",
    "insights.categoryRisk": "リスク管理",
    "insights.categoryExplainable": "説明可能AI",

    // AI Agent Quant Myth Article
    "insights.aiAgentMyth.title": "AIエージェント量化研究：冷静な検証実験",
    "insights.aiAgentMyth.description": "QuantaAlphaで対照実験を実施：Alpha158ベースライン vs LLM因子マイニング vs 進化戦略。バックテスト結果から得られた示唆。",
    "insights.aiAgentMyth.badgeCritical": "所見",
    "insights.aiAgentMyth.lead": "学術界のAIエージェント論文は多数ある：LLMによる自動因子マイニング、進化戦略、マルチエージェント協調……実際に実験してみた結果を共有する。",
    "insights.aiAgentMyth.sectionDesign": "実験設計",
    "insights.aiAgentMyth.designText": "QuantaAlphaを使用、CSI300市場、2022年サンプル外バックテスト。3群比較：青線 Alpha158ベースライン（20因子、マイニングなし）｜橙線 QuantaAlpha 進化なし｜緑線 QuantaAlpha 進化版（Dir=2, Rounds=3）",
    "insights.aiAgentMyth.sectionData": "データが語る",
    "insights.aiAgentMyth.dataSource": "batch_summary.json および累積超過リターン CSV より（2022-01-04〜2022-12-30、CSI300 ベンチマーク比）：",
    "insights.aiAgentMyth.dataRow1": "alpha158_20（ベースライン、20因子、マイニングなし）",
    "insights.aiAgentMyth.dataRow2": "combined_fresh_exp2（QuantaAlpha シード、進化なし）",
    "insights.aiAgentMyth.dataRow3": "combined_fresh_exp4（QuantaAlpha 進化版、Dir=2 Rounds=3）",
    "insights.aiAgentMyth.dataColExperiment": "実験",
    "insights.aiAgentMyth.dataColReturn": "累積超過リターン",
    "insights.aiAgentMyth.dataColMaxDD": "最大ドローダウン",
    "insights.aiAgentMyth.dataColRankIC": "Rank IC",
    "insights.aiAgentMyth.dataDD1": "-9.20%",
    "insights.aiAgentMyth.dataDD2": "-7.11%",
    "insights.aiAgentMyth.dataDD3": "-11.54%",
    "insights.aiAgentMyth.dataIC1": "0.0325",
    "insights.aiAgentMyth.dataIC2": "—",
    "insights.aiAgentMyth.dataIC3": "—",
    "insights.aiAgentMyth.dataVal1": "+13.69%",
    "insights.aiAgentMyth.dataVal2": "-0.78%",
    "insights.aiAgentMyth.dataVal3": "-1.13%",
    "insights.aiAgentMyth.dataText2": "つまり：本実験では、LLMマイニング・進化に相当な計算資源を投じても、20個の古典的量価因子を上回る結果にはならなかった。",
    "insights.aiAgentMyth.sectionReflect": "所感",
    "insights.aiAgentMyth.reflectText1": "AIエージェントの価値を否定するわけではない——可能性はある。しかし多くの論文の実験設計は吟味に耐えない。Cherry-pickされた期間、甘いベースライン、発表後の再現性軽視——こうした「まじめなデタラメ」はトップ学会でも珍しくない。",
    "insights.aiAgentMyth.reflectText2": "クオンツで最も恐れるのは自己満足だ。儲かる戦略が本質。エージェントは役立つか？ひょっとしたら。だがまず本物のバックテスト結果を見せてほしい——fancyなフレームワークでごまかさずに。",
    "insights.aiAgentMyth.footer": "SAIL Lab · データ先行、結論は後から",
    "insights.aiAgentMyth.date": "2026年3月",
    "insights.aiAgentMyth.readTime": "4分で読める",

    // ML Continuous Learning / DeepAgent FX Article
    "insights.mlContinuousLearning.title": "MLフィルター vs ベースライン：XAUUSDにおける継続学習の重要性",
    "insights.mlContinuousLearning.description": "DeepAgent FXをMQL5・GogoJungleで販売開始。XAUUSD実口座で約3営業日+$1,113。AIフィルター vs ベースライン、パイプラインと継続学習。",
    "insights.mlContinuousLearning.badgeContinuous": "継続学習",
    "insights.mlContinuousLearning.launchLabel": "新製品リリース",
    "insights.mlContinuousLearning.launchText": "今月、新開発のEA「DeepAgent FX」をMQL5 MarketとGogoJungleにて販売開始しました。ノーマーチンゲール・ノーヘッジ設計。大規模市場データで学習した次世代FX AIエージェントです。",
    "insights.mlContinuousLearning.differentiatorText": "DeepAgent FXが他の数千のEAと決定的に違う点は何か。AIがフィルターを担うこと。トレンドエンジンが生成した各候補トレードは、実行前に必ず機械学習モデルのアンサンブル審査を通過します。以下は、そのフィルターが実際にもたらす差です。",
    "insights.mlContinuousLearning.lead": "DeepAgent FXは実口座で稼働中。AIアンサンブルフィルターがトレンドエンジンと約定の間に入り、低品質なセットアップを排除し、モデルが認めたトレードだけを実行します。以下：ライブ結果、その後フィルターの重要性。",
    "insights.mlContinuousLearning.date": "2026年3月",
    "insights.mlContinuousLearning.readTime": "12分で読める",
    "insights.mlContinuousLearning.sectionLiveTrading": "ライブ取引：DeepAgent FX · XAUUSD",
    "insights.mlContinuousLearning.sectionLiveTradingDesc": "実口座のMT5取引 — バックテストではありません。6月22日入金 $1,456.57 → 6月26日残高 $2,570.17。約3営業日で純利益 +$1,113.60（+76.45%）。ノーマーチンゲール・ノーヘッジ。",
    "insights.mlContinuousLearning.liveImageCaption": "MT5モバイル取引履歴 — XAUUSD、2026.06.22–26",
    "insights.mlContinuousLearning.liveStatDeposit": "初期入金",
    "insights.mlContinuousLearning.liveStatBalance": "残高",
    "insights.mlContinuousLearning.liveStatProfit": "純利益",
    "insights.mlContinuousLearning.liveStatGrowth": "成長率",
    "insights.mlContinuousLearning.liveNote": "掲載結果は内部研究版（AIモデルを約3日ごとに再学習）によるものです。マーケットプレイス版は固定モデルです。継続的なライブ成績はフォワードテストパネルをご参照ください。",
    "insights.mlContinuousLearning.sectionComparison": "AIフィルターがもたらす差",
    "insights.mlContinuousLearning.sectionComparisonDesc": "同じトレンド戦略で、AIアンサンブルフィルターON vs OFF — フィルターがルールシグナルを選別された高品質トレードへ変える。",
    "insights.mlContinuousLearning.colMetric": "指標",
    "insights.mlContinuousLearning.colML": "AIフィルターあり",
    "insights.mlContinuousLearning.colBaseline": "AIフィルターなし",
    "insights.mlContinuousLearning.colDelta": "Δ",
    "insights.mlContinuousLearning.metricProfit": "純利益",
    "insights.mlContinuousLearning.metricTrades": "総取引数",
    "insights.mlContinuousLearning.metricPF": "プロフィットファクター",
    "insights.mlContinuousLearning.metricPayoff": "期待値",
    "insights.mlContinuousLearning.metricDD": "ドローダウン %",
    "insights.mlContinuousLearning.metricRecovery": "リカバリーファクター",
    "insights.mlContinuousLearning.metricSharpe": "シャープレシオ",
    "insights.mlContinuousLearning.cardSelectivityTitle": "選択性",
    "insights.mlContinuousLearning.cardSelectivityDesc": "MLが低品質なセットアップを排除。取引数は減り、1取引あたりのedgeは向上。",
    "insights.mlContinuousLearning.cardRiskTitle": "リスク",
    "insights.mlContinuousLearning.cardRiskDesc": "ドローダウンは32.5%→21.8%。リカバリーファクター5.55 vs 0.58。",
    "insights.mlContinuousLearning.cardConsistencyTitle": "安定性",
    "insights.mlContinuousLearning.cardConsistencyDesc": "Sharpe 15.81 vs 2.35 — リターンだけでなく、エクイティカーブも滑らか。",
    "insights.mlContinuousLearning.sectionPipeline": "DeepAgent FXパイプライン：MLが入る位置",
    "insights.mlContinuousLearning.sectionPipelineDesc": "ルールベーストレンドエンジンが候補生成 → AIアンサンブルでフィルター → 信頼度スコア → 動的サイジング → MT5実行 → フィードバックループ",
    "insights.mlContinuousLearning.sectionStages": "6段階：データからライブ取引へ",
    "insights.mlContinuousLearning.stage1Title": "① マーケットデータ",
    "insights.mlContinuousLearning.stage1Desc": "数百万本のM5バー＋ティックデータ。価格、トレンド、ボラティリティ、レジーム、出来高。",
    "insights.mlContinuousLearning.stage2Title": "② トレンドポリシーエンジン",
    "insights.mlContinuousLearning.stage2Desc": "EMAプルバックルール — ベースライン戦略（まだMLなし）。",
    "insights.mlContinuousLearning.stage3Title": "③ AIアンサンブルフィルター",
    "insights.mlContinuousLearning.stage3Desc": "Random Forest、XGBoost、CatBoost、Logistic Regression＋キャリブレーション済みコンセンサス。",
    "insights.mlContinuousLearning.stage4Title": "④ トレード信頼度スコア",
    "insights.mlContinuousLearning.stage4Desc": "方向別閾値（例：Long 0.32 / Short 0.28）。弱いシグナルは拒否。",
    "insights.mlContinuousLearning.stage5Title": "⑤ 動的ポジションサイジング",
    "insights.mlContinuousLearning.stage5Desc": "モデル信頼度に応じてロット倍率を調整（1x–3x）。",
    "insights.mlContinuousLearning.stage6Title": "⑥ MT5ライブ実行",
    "insights.mlContinuousLearning.stage6Desc": "ONNXモデルをEAに組み込み。トレーリングストップ＋セッションリスク管理。",
    "insights.mlContinuousLearning.sectionContinuous": "なぜ継続学習が不可欠か",
    "insights.mlContinuousLearning.continuousP1": "静的なMLモデルは過去のスナップショットに過ぎません。金のレジームは変化し続けます — ボラティリティクラスター、セッション構造、マクロイベントが相関を書き換えます。ベースライン（Pass 0）には適応機構がなく、現在の市場品質に関係なくすべてのルールシグナルを発火します。",
    "insights.mlContinuousLearning.loopTitle": "継続学習ループ",
    "insights.mlContinuousLearning.loop1": "バッチバックテスト — 全取引＋エントリー時20特徴量を収集",
    "insights.mlContinuousLearning.loop2": "Walk-forward選定 — 30%のサンプル外データで最良モデルを選択",
    "insights.mlContinuousLearning.loop3": "全量refit — 直近100%ウィンドウでデプロイモデルを再学習（Python＋MT5 ONNX整合）",
    "insights.mlContinuousLearning.loop4": "方向別デプロイ — Long/Short別モデルと閾値をMT5 EAへ同期",
    "insights.mlContinuousLearning.loop5": "パフォーマンスフィードバック — ライブ結果を次のバッチサイクルへ（目標：約3日ごとに再学習）",
    "insights.mlContinuousLearning.keyInsightTitle": "要点",
    "insights.mlContinuousLearning.keyInsightText": "Pass 1のML優位性は魔法ではなく、直近の取引結果から学習した選択性です。継続再学習がなければedgeは衰えます。ループを回せば、フィルターは「今日実際に取引している市場」に合わせて校正され続けます。",
    "insights.mlContinuousLearning.sectionTakeaways": "まとめ",
    "insights.mlContinuousLearning.takeaway1": "MLはトレンド戦略を置き換えない — フィルターする。",
    "insights.mlContinuousLearning.takeaway2": "同じルールで：3倍の利益、半分の取引数、ドローダウン約1/3減。",
    "insights.mlContinuousLearning.takeaway3": "方向別モデル（Long ≠ Short）は単一共通閾値より優れる。",
    "insights.mlContinuousLearning.takeaway4": "継続学習がループを閉じる：ライブ → データ → 再学習 → デプロイ → ライブ。",
    "insights.mlContinuousLearning.takeaway5": "PythonライブフィルターとMT5 ONNX EAは同一の判断ロジックを共有。",
    "insights.mlContinuousLearning.footer": "SAIL Lab · 東京 · AI × データ × 戦略 × リスク管理",
    "insights.mlContinuousLearning.backLink": "← Insightsに戻る",
    "insights.mlContinuousLearning.linkMql5": "MQL5 Market",
    "insights.mlContinuousLearning.linkGogoJungle": "GogoJungle",

    // Common
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.retry": "再試行",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}